workspace:
  base: /opt
  path: src

pipeline:
  build:
    image: hungo/aws-cli-test
    secrets: [ h_key, h_token, h_location ]
    commands:
      - export AWS_ACCESS_KEY_ID="$H_KEY"
      - export AWS_SECRET_ACCESS_KEY="$H_TOKEN"
      - export AWS_DEFAULT_REGION="$H_LOCATION"
      - cd /root/
      - ./getBuild.sh
      - if [[ "${DRONE_TAG}" != "" ]]; then echo notempty; else exit 0; fi
      - echo "443"
      - echo "999"
    when:
        event: [tag]
